### ISSUE TITLE
Add latest library to elm-get repository

### ISSUE THREAD

**Issue by jcollard** [timthelion/elm-key-constants#2]
When you get a chance, could you run `elm-get publish` on the latest version?

**Comment by timthelion** [comment]
Could you please do it yourself?  I've added you as a collaborator on the repo so you should be able to do any tagging that needs to be done.  I tried to do this but I don't use Elm anymore and I had some trouble installing from git.  If you don't want to I'll try to install elm again.  Sorry for not getting back to you on this, that was rude :(

**Comment by timthelion** [comment]
Or if you want to publish your own fork I won't protest ;)

**Comment by jastice** [comment]
The currently published version (1.1) doesn't work with elm-server because of the missing dependencies declaration. Will you publish, @jcollard?

**Comment by jcollard** [comment]
@jastice, you should install jcollard/elm-key-constants. Even though it isn't published, it will still install with elm-get.

**Comment by timthelion** [comment]
@jcollard can you publish yours?  Can I unpublish mine?

**Comment by jcollard** [comment]
I don't believe there is a way to unpublish by yourself. I think you will need to contact Evan directly an ask him to manually remove the library. I have been holding off publishing mine because I want to add an `Eq` style type for comparing KeyCodes. I have not had the time to do this but I will go ahead and publish it in its current state.

**Comment by jcollard** [comment]
@jastice I've just published it as `jcollard/key-constants`.

**Comment by timthelion** [comment]
Evan just wrote me that my version is unpublished.

**Comment by jastice** [comment]
thanks!
